### ISSUE TITLE
QlikSense Desktop is getting Crashed

### ISSUE THREAD

**Issue by tauceef9** [ajaykakkar93/QlikSense-Sheet-Styler-Lite#1]
Hi,

Whenever I am trying to change settings of any object qliksense desktop is getting crashed again and again.

I am having 11.11.2 version.

Below is the error when it is getting crashed:
---------------------------
QlikSenseBrowser.exe - Application Error
---------------------------
The instruction at 0x00000000543B6C2A referenced memory at 0xFFFFFFFFFFFFFFFF. The memory could not be read.
---------------------------

Regards,
Tauceef

**Comment by ajaykakkar93** [comment]
Do you have the latest extension

**Comment by tauceef9** [comment]
Hi Ajay,

Thanks for your response.
I have downloaded it from below link:
https://github.com/ajaykakkar93/QlikSense-Sheet-Styler-Lite

Which I think is the latest one.

Regards,
Tauceef

**Comment by tauceef9** [comment]
Hi Ajay,

Are you able to find anything on this? today I found one thing that it's not about editing the properties, even when I work on different objects properties it is getting crashed but when I remove this extension everything works fine.

I really like the extension and want to used it in my app. Looking forward for your response.

Regards,
Tauceef

**Comment by ajaykakkar93** [comment]
Remove and add extension again from the sheet

**Comment by ajaykakkar93** [comment]
Hi I am going to release a update to this extension soon that might solve your issue.
