### ISSUE TITLE
Problems with the background

### ISSUE THREAD

**Issue by EduardoQlik20** [ajaykakkar93/QlikSense-Sheet-Styler-Lite#10]
Does not respect the image that is placed as a background. I'm placing a .png image that I have in the image folder ... Sense \ Content \ Default. Do you know why this happens?
By the way I use the February 2019 version of QlikSense.

**Comment by ajaykakkar93** [comment]
Please Use this:
**https://github.com/ajaykakkar93/Qlik-Sense-Styler-Mashup**

**Comment by ajaykakkar93** [comment]
https://github.com/ajaykakkar93/Qlik-Sense-Styler-Mashup

**Comment by imtiazu** [comment]
Sorry I don’t see how this is supposed to work vs the lite extension. It doesn’t make sense. Have you got some instructions please?
