### ISSUE TITLE
The downloadable extension doesn't match the one used in the youtube video.

### ISSUE THREAD

**Issue by rileycf1** [ajaykakkar93/QlikSense-Sheet-Styler-Lite#3]
The video shows where you can display the css file.  The top menu item is "Select Style Type" which isn't on the downloadable extension.

**Comment by rileycf1** [comment]
Sorry, found out what I did wrong.  Thanks

**Comment by ajaykakkar93** [comment]
😂 it's fine rileycf1 I am going to update this extension again with more options. Stay tuned

**Comment by rileycf1** [comment]
Thanks Ajay!

               Chuck
