### ISSUE TITLE
Object title hyperlink?

### ISSUE THREAD

**Issue by maelafifi** [ajaykakkar93/QlikSense-Sheet-Styler-Lite#5]
Hi Ajay, 

I would like to add the functionality to make the object header a link. Any chance you are familiar with this kind of requirement?

Essentially, I'd like for an object title to read "Table 1 - Click to view trends" and when you click on the object title, it will redirect you to another sheet that shows more information about a given table.

**Comment by ajaykakkar93** [comment]
Hi Elafifi,
Thank you for this idea i have already done something similar to this & it will be on GitHub after some time....
If you have something else feel free to ping me.

**Comment by ajaykakkar93** [comment]
This might help you

https://github.com/ajaykakkar93/Qlik-Sense-Dialog-Box
