### ISSUE TITLE
Filterpane color not changing & sheet theme color not working properly

### ISSUE THREAD

**Issue by ankitarath2011** [ajaykakkar93/QlikSense-Sheet-Styler-Lite#6]
Hi,

I have changed the background color of objects to black (#000000) in object styling and advanced settings. But filter pane background color is not changing.

There is another issue I am facing. When I am changing the sheet style to Dark theme or some other theme the object background color that I had changed to black is automatically modified to while once I am saving the changes and reopening the sheet.

Please suggest. It is urgent.

Ankita

**Comment by ajaykakkar93** [comment]
Hi, I have updated the extension it should  work now
