### ISSUE TITLE
Custom Google font not working

### ISSUE THREAD

**Issue by EladKush** [ajaykakkar93/QlikSense-Sheet-Styler-Lite#7]
Hello,
This is a wonderful extenssion!
Though when i'm trying to custom font by Custom Google Font i receive the same result (the same font) no matter what font i choose. I switch fonts but get the same font on screen.
Thank you!

**Comment by ajaykakkar93** [comment]
https://fonts.googleapis.com/css?family=FONTNAME

is this URL accesable?
