### ISSUE TITLE
Changing the Background Color of the Sheet

### ISSUE THREAD

**Issue by Wmlau69** [ajaykakkar93/QlikSense-Sheet-Styler-Lite#8]
Is it possible to drop the extension onto my sheet and not have it automatically change the look of the objects that are already on my sheet?  I just want to change the background color of the sheet and nothing else.  I don't want the extension to even change the background color of the objects like the bar charts and gauges.

**Comment by ajaykakkar93** [comment]
Hi,
What version is qlik sense are you using..?

**Comment by Wmlau69** [comment]
September 2017 release

Sent from my iPhone

> On Oct 3, 2018, at 10:12 PM, Ajay Kakkar <notifications@github.com> wrote:
> 
> Hi,
> What version is qlik sense are you using..?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
____________________________________________________________
Unbelievable German World War 2 Photo Shocks Americans
pro.healthresponses.org
http://thirdpartyoffers.netzero.net/TGL3231/5bb58346ba1bc345109dst04vuc

**Comment by ajaykakkar93** [comment]
Ok then so your requirement it to change the background colour of sheet rest remains the same, that right??

**Comment by Wmlau69** [comment]
Yes.  When i get to the office later, i will send you a screenshot of what i want.

Sent from my iPhone

> On Oct 3, 2018, at 11:24 PM, Ajay Kakkar <notifications@github.com> wrote:
> 
> Ok then so your requirement it to change the background colour of sheet rest remains the same, that right??
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
____________________________________________________________
1 Simple Trick Removes Eye Bags & Lip Lines in Seconds
ourhealthpros.com
http://thirdpartyoffers.netzero.net/TGL3231/5bb5f17342dd5717230a2st04duc

**Comment by Wmlau69** [comment]
Here's an example of a sheet where we used the original Qlik Sense Styler to change the background of the sheet to light gray.  What we like about this is that if you have so many objects on your sheet, the gray background creates a border to separate everything.  What we don't like about this extension is that it changes things other than the background color.  I don't have it shown here in this sheet but if I use this extension on this sheet and specify that I only want the change applied to this sheet, the background color on other sheets are changed or the font sizes on the sheet title or KPI objects change.

I found another extension that just changes the background color of the sheet but it also changes the background color of the objects on the sheet as well.  

Is there a way to use your extension where we just change the color of the sheet and nothing else?  We don't even want to change the background color of the objects on the sheet.
____________________________________________________________
Stock-Picking Legend Leaks Secret Stock, Trades Less Than $3
pro.oxfordclub.com
http://thirdpartyoffers.netzero.net/TGL3231/5bb60e3f251f4e3f731bst04vuc

**Comment by ajaykakkar93** [comment]
Ok I got it just the background colour... I'll add another extension that will change to desired background colour , border for objects and shadow to make it more interactive.... I'll intimate you when I am done.

**Comment by ajaykakkar93** [comment]
If you are Interested in basic training.. I'll provide you with the content...and you can make this extension by yourself

**Comment by Wmlau69** [comment]
Thanks  Basic training is on my calendar.  It's a matter of finding the time to go through the training.
____________________________________________________________
This Simple Method "Ends" Tinnitus - Try Tonight
fighttinnitusnow.com
http://thirdpartyoffers.netzero.net/TGL3231/5bb7560e44352560e7e44st02vuc

**Comment by ajaykakkar93** [comment]
Ok I'll give you a new extension just for that..

**Comment by Wmlau69** [comment]
Did you post that extension on glithub?

Sent from my iPhone

> On Oct 5, 2018, at 8:17 AM, Ajay Kakkar <notifications@github.com> wrote:
> 
> Ok I'll give you a new extension just for that..
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
____________________________________________________________
Unbelievable German World War 2 Photo Shocks Americans
pro.healthresponses.org
http://thirdpartyoffers.netzero.net/TGL3231/5bbeb48ee7e57348e7f0bst01duc

**Comment by Wmlau69** [comment]
Did you ever put out that new extension to just change the background color?


____________________________________________________________
One Cup of This (Before Bed) Burns Belly Fat Like Crazy
Celebrity Local
http://thirdpartyoffers.netzero.net/TGL3231/5bf4841f757a941f6c75st04vuc

**Comment by imtiazu** [comment]
Hey Ajay – I am using the previous extension as I am dynamically loading values from a database per client. As my dashboards are multi-tenant, I want different colours to appear dynamically which I am holding in my brands database. Will the new version support this?

**Comment by ajaykakkar93** [comment]
https://github.com/ajaykakkar93/Qlik-Sense-Styler-Mashup
