### ISSUE TITLE
Extension is not working in QS Feb 2019 version

### ISSUE THREAD

**Issue by arsalash** [ajaykakkar93/QlikSense-Sheet-Styler-Lite#9]
Hi Ajay,

Extension is not working in QS Feb 2019 version. Can you provide us the updated version?

Many Thanks.

**Comment by arsalash** [comment]
@ajaykakkar93 do you have any update?

**Comment by ajaykakkar93** [comment]
Can you share issue which you are facing...??
In detail so I can get a idea.

**Comment by arsalash** [comment]
The issue is that I am trying to add the extension on sheet but It's not adding. It's working fine in June 2018 and but on Feb 2019 it's not working.

**Comment by lennyvz** [comment]
Existing Styler objects remain, but many of the properties no longer affect the sheet they are supposed to be styling.

**Comment by lennyvz** [comment]
Background color specifically is one that we use extensively

**Comment by imtiazu** [comment]
Hey there, amazing extension! Feb2019 has some issues.

1. Background color/img doesn't work - just nothing appears.
2. Selections toolbar background color doesn't work (if I hack away the Qlik default css color then it does so assume a css change in their recent release?). Default color in Qlik stays.
![image](https://user-images.githubusercontent.com/11614992/53915920-2ea3c180-4061-11e9-86cb-4bd180e9a22b.png)

3. After any changes when editing, a full page refresh is required to see the changes saved. Not the end of the world just need to refresh a fair bit.

But seriously, amazing extension - great job!
Thanks

**Comment by ajaykakkar93** [comment]
Thanks for details now I know where to start I'll de the changes n update a new package..

**Comment by ajaykakkar93** [comment]
Will you use Theme API i am going to add a **New Styler** which will help you to make **a theme** easily just by filing a form.
ill share the **MASHUP** on this link as well.

**Comment by imtiazu** [comment]
I'm not using the theme api but happy to check it out. I love the current extension to be honest.

**Comment by imtiazu** [comment]
FYI , object background color stopped working too when styling for each object.
![image](https://user-images.githubusercontent.com/11614992/54033110-bc8fc180-41b3-11e9-8510-9fdb8d5b96e2.png)

It works fine when using globally here:
![image](https://user-images.githubusercontent.com/11614992/54033145-d29d8200-41b3-11e9-971f-eb250e4defd8.png)

**Comment by ajaykakkar93** [comment]
Mashup is out for download to make a beautiful theme with qlik sense theming api

https://github.com/ajaykakkar93/Qlik-Sense-Styler-Mashup

**Comment by ajaykakkar93** [comment]
All these above issues can be solved i think on a major level.
Thank you for all your comments it helped me to learn n detect bugs, major & mior changes in qlik as well.
